---
apiVersion: v1
kind: ConfigMap
metadata:
  name: default-pod-template
  namespace: tekton-pipelines
data:
  podTemplate: |
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      fsGroup: 1000
    containers:
    - name: "*"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: RuntimeDefault
