apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: sample-pipeline-run
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: sample-pipeline
  podTemplate:
    securityContext:
      runAsUser: 1000
      runAsNonRoot: true
      fsGroup: 1000
    containers:
    - name: "*"
      securityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - "ALL"
        seccompProfile:
          type: RuntimeDefault
