apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: relaxed-psp
  namespace: tekton-pipelines
spec:
  allowPrivilegeEscalation: true
  allowedCapabilities:
  - '*'
  runAsUser:
    rule: 'RunAsAny'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'
  volumes:
  - '*'
  seccompProfiles:
  - '*'
  hostPID: true
  hostIPC: true
  hostNetwork: true
  hostPorts:
  - min: 0
    max: 65535
# ---
# apiVersion: policy/v1beta1
# kind: PodSecurityPolicy
# metadata:
#   name: psp-tekton
# spec:
#   allowPrivilegeEscalation: false
#   allowedCapabilities:
#   - '*'
#   runAsUser:
#     rule: 'MustRunAsNonRoot'
#   seLinux:
#     rule: 'RunAsAny'
#   supplementalGroups:
#     rule: 'RunAsAny'
#   fsGroup:
#     rule: 'RunAsAny'
#   volumes:
#   - '*'
#   seccompProfiles:
#   - 'RuntimeDefault'
