---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cronjob-sa
  namespace: my-namespace
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-sa-role
  namespace: my-namespace
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelines"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["create"] # [ get, watch, list, update, patch, create, delete ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-sa-rolebinding
  namespace: my-namespace
subjects:
- kind: ServiceAccount
  name: cronjob-sa
roleRef:
  kind: Role
  name: cronjob-sa-role
  apiGroup: rbac.authorization.k8s.io
