---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cronjob-sa-role
  namespace: tekton-pipelines
rules:
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns", "pipelines"]
  verbs: ["get", "watch", "list"]
- apiGroups: ["tekton.dev"]
  resources: ["pipelineruns"]
  verbs: ["create"] # [ get, watch, list, update, patch, create, delete ]