---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cronjob-sa-rolebinding
  namespace: tekton-pipelines
subjects:
- kind: ServiceAccount
  name: cronjob-sa
roleRef:
  kind: Role
  name: cronjob-sa-role
  apiGroup: rbac.authorization.k8s.io
