apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sample-pipeline
spec:
  tasks:
  - name: sample-task-1
    taskRef:
      name: sample-task-1
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: sample-cron-job
spec:
  schedule: "*/2 * * * *" # Runs every 2 minutes
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: pipeline
          containers:
          - name: trigger
            image: docker.io/my-linux-image:v0.1
            command: ["tkn"]
            args: ["pipeline", "start", "sample-pipeline"]
          restartPolicy: OnFailure
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sample-task-1
spec:
  steps:
  - name: task-1
    image: docker.io/my-linux-image:v0.1
    env:
    - name: SAMPLE_SECRET
      valueFrom:
        secretKeyRef:
          name: "sample-secret"
          key: "sample-secret"
    - name: SAMPLE_ENV_VAR
      value: "this-is-a-sample-environment-variable from task1!"
    script: |
      #!/bin/bash
      echo "hello, world! from task1"
      echo "SAMPLE_SECRET: ${SAMPLE_SECRET}"
      echo "SAMPLE_ENV_VAR: ${SAMPLE_ENV_VAR}"
